#!/bin/bash - 
#===============================================================================
#
#          FILE: add_cover_mp3
# 
#         USAGE: ./add_cover_mp3 
# 
#   DESCRIPTION: Fügt allen MP3s in einem Verzeichnis ein Cover (APIC Frame)
#		 hinzu, wenn dieses Verzeichnis ein JPG oder ein PNG enthält.
#		 Bereits vorhandene APIC Frames werden gelöscht.
#		 PNGs werden bevorzugt behandelt. Nach dem Hinzufügen werden
#		 die Bilder gelöscht. Der Name der Bilder muss 'cover.png'
#		 oder 'cover.jpg' sein
# 
#       OPTIONS: ---
#  REQUIREMENTS: eyeD3
#          BUGS: ---
#         NOTES: ---
#        AUTHOR: Andreas Böttger (aboettger), andreas.boettger@gmx.de
#  ORGANIZATION: 
#       CREATED: 14.04.2014 12:33
#      REVISION:  ---
#===============================================================================

#set -o nounset                              # Treat unset variables as an error

cd
cd Musik
shopt -s nullglob
shopt -s nocaseglob
find -depth  -type d | { while read -r D;
  do
    JPG="$D/cover.jpg"
    PNG="$D/cover.png"
    mp3="$D/*.mp3"
    
    if [ "$mp3" != "" ] && [ "$D" != "." ]
    then
      # PNGs werden bevorzugt
      if [ -f "$PNG" ]
      then
        echo "PNG in $D"
        find "$D" -type f -maxdepth 1 -name "*.mp3" -print0 |xargs -0 eyeD3 --remove-images
        find "$D" -type f -maxdepth 1 -name "*.mp3" -print0 |xargs -0 eyeD3 -F '~' --add-image="$D"/cover.png~FRONT_COVER
        
        # Wenn ein PNG vorhanden ist, dann will ich keine JPGs mehr
        if [ -f "$JPG" ]
        then
          rm "$D"/cover.jpg
        fi
        rm "$D"/cover.png
      else
        if [ -f "$JPG" ]
        then
          echo "JPG in $D"
	  find "$D" -type f -maxdepth 1 -name "*.mp3" -print0 |xargs -0 eyeD3 --remove-images
          find "$D" -type f -maxdepth 1 -name "*.mp3" -print0 |xargs -0 eyeD3 -F '~' --add-image="$D"/cover.jpg~FRONT_COVER
          rm "$D"/cover.jpg
        fi
      fi
    fi
done }
