#!/bin/bash - 
#===============================================================================
#
#          FILE: add_cover_flac
# 
#         USAGE: ./add_cover_flac
# 
#   DESCRIPTION: Fügt allen FLACSs in einem Verzeichnis ein Cover (APIC Frame)
#		 hinzu, wenn dieses Verzeichnis ein JPG oder ein PNG enthält.
#		 Bereits vorhandene APIC Frames werden gelöscht.
#		 PNGs werden bevorzugt behandelt. Nach dem Hinzufügen werden
#		 die Bilder gelöscht.
# 
#       OPTIONS: ---
#  REQUIREMENTS: ---
#          BUGS: ---
#         NOTES: ---
#        AUTHOR: Andreas Böttger (aboettger), andreas.boettger@gmx.de
#  ORGANIZATION: 
#       CREATED: 14.04.2014 12:33
#      REVISION:  ---
#===============================================================================

#set -o nounset                              # Treat unset variables as an error

cd
cd Musik
shopt -s nullglob
shopt -s nocaseglob
find -depth  -type d | { while read -r D;
  do
    JPG="$D/cover.jpg"
    PNG="$D/cover.png"
    flac="$D/*.flac)"
    
    if [ "$flac" != "" ]  && [ "$D" != "." ]
    then
      # PNGs werden bevorzugt
      if [ -f "$PNG" ]
      then
        echo "$D"
        find "$D" -type f -maxdepth 1 -name "*.flac" -print0 |xargs -0 metaflac --remove --block-type=PICTURE
        find "$D" -type f -maxdepth 1 -name "*.flac" -print0 |xargs -0 metaflac --import-picture-from="$D"/cover.png
        
        # Wenn ein PNG vorhanden ist, dann will ich keine JPGs mehr
        if [ -f "$JPG" ]
        then
          rm "$D"/cover.jpg
        fi
        rm "$D"/cover.png
      else
        if [ -f "$JPG" ]
        then
          echo "$D"
          find "$D" -type f -maxdepth 1 -name "*.flac" -print0 |xargs -0 metaflac --remove --block-type=PICTURE
          find "$D" -type f -maxdepth 1 -name "*.flac" -print0 |xargs -0 metaflac --import-picture-from="$D"/cover.jpg
          rm "$D"/cover.jpg
        fi
      fi
    fi
done }
