#!/bin/bash -
#===============================================================================
#
#          FILE: add_cover_mp3
#
#         USAGE: ./add_cover_mp3 start_directory
#
#   DESCRIPTION: Fügt allen MP3s in einem Verzeichnis ein Cover (APIC Frame)
#		 hinzu, wenn dieses Verzeichnis ein JPG oder ein PNG enthält.
#		 Bereits vorhandene APIC Frames werden gelöscht.
#		 PNGs werden bevorzugt behandelt. Nach dem Hinzufügen werden
#		 die Bilder gelöscht. Der Name der Bilder muss 'cover.png'
#		 oder 'cover.jpg' sein
#
#       OPTIONS: ---
#  REQUIREMENTS: eyeD3
#          BUGS: ---
#         NOTES: ---
#        AUTHOR: Andreas Böttger (aboettger), andreas.boettger@gmx.de
#  ORGANIZATION:
#       CREATED: Fr 25 Apr 2014 17:17:43 CEST
#      REVISION:  ---
#===============================================================================

#set -o nounset                              # Treat unset variables as an error

shopt -s nullglob
shopt -s nocaseglob

add_cover() {
  red="\e[0;31m"
  green="\e[0;32m"
  NC="\e[0m" # No Color
  
  find "$1" -depth -type f -name "$2"  | { while read -r image_path;
    do
      echo -e "${green}Cover found:${NC} $image_path"
      dir_name=$(dirname "$image_path")
      
      mp3s=$(find "$dir_name" -maxdepth 1 -type f -name '*.mp3' | wc -l)
      
      echo -e "${green}MP3s found:${NC} $mp3s"
      
      if [ "$mp3s" != "0" ]
      then
        find "$dir_name" -maxdepth 1 -type f -name "*.mp3" -print0 |xargs -0 eyeD3 --remove-images
        find "$dir_name" -maxdepth 1 -type f -name "*.mp3" -print0 |xargs -0 eyeD3 -F '~' --add-image="$image_path"~FRONT_COVER
        
        rm "$image_path"
      fi
      echo
    done
  }
}

if [ "$1" == "" ]
then
  echo "Please specify a start directory."
else
  # PNGs werden bevorzugt
  add_cover "$1" cover.png
  add_cover "$1" cover.jpg
fi
exit 0

