#!/bin/bash
#
# I use this script together with the programs "gmusicbrowser" and "picard".
# With each song change this script is called and decided whether the program
# "picard" should be started or not.
#

dir=$(dirname "$1")

if [ "$dir" == "" ]
then
  echo "The supplied folder name is empty."
  exit 1
fi

if [ "$(ls -A "$dir")" == "" ]; then
  echo "The supplied folder '$dir' is empty."
  exit 1
fi

fileNameTodayPlayed="/tmp/gmb_call_picard_history"
matchedValue=""

if [ ! -f "$fileNameTodayPlayed" ]
then
  echo "File "$fileNameTodayPlayed" doesn't exists, I will create the file."
  touch "$fileNameTodayPlayed"
else
  dirEscaped=${dir//\[/\\[}
  dirEscaped=${dirEscaped//\]/\\]}
  matchedValue=$(grep "$dirEscaped" "$fileNameTodayPlayed")
fi

# Don't call picard, if the album '$dir' is already in the list of recently played albums.
if [ "$matchedValue" != "" ]
then
  echo "---- Don't call picard, the album '$dir' is already in the list of recently played albums: '$fileNameTodayPlayed'"
else
  echo "++++ Call picard, the album '$dir' is not in the list of recently played albums: '$fileNameTodayPlayed'"
  echo "$dir" >> "$fileNameTodayPlayed"
  picard "$dir"
fi

exit 0
