#!/bin/bash

values=$(yad \
  --form \
  --field=Suchbegriff \
  --field=Pfad \
  --class="List-PDF-Pattern" \
  --name="List PDF Pattern" \
  --title="Suchbegriff und Verzeichnis" \
  --center \
  --separator="~/~" \
)
pattern=$(echo $values | awk -F "~/~" '{print $1}')
[[ -z "$pattern" ]] && exit 1

path=$(echo $values | awk -F "~/~" '{print $2}')
[[ -z "$path" ]] && exit 1

exec 3> >(yad \
  --center \
  --class="List-PDF" \
  --name="List PDF" \
  --text="Der Suchbegriff \"$pattern\" wurde in diesen PDFs gefunden" \
  --save \
  --list \
  --column="Gefunden in" \
  --button="Close:1" \
  --width=700 \
  --height=500 \
  --title="Select a PDF..." \
  --dclick-action="xdg-open" \
  --quoted-output\
  --listen \
)

#exec 4> >(yad --progress --pulsate --auto-close --center)

pdfgrep -r "$pattern" "$path" 2> /dev/null | awk -F ":" '{out=$2; for(i=3;i<=NF;i++){out=out":"$i}; print $1}' | uniq >&3

exec 3>&-
#exec 4>&-

exit 0
