#!/bin/bash -
#===============================================================================
#
#          FILE: pull_all_vcs
#
#         USAGE: ./pull_all_vcs
#
#   DESCRIPTION:
#
#       OPTIONS: ---
#  REQUIREMENTS: ---
#          BUGS: ---
#         NOTES: ---
#        AUTHOR: andreas.boettger@gmx.de
#  ORGANIZATION:
#       CREATED: Do 24 Apr 2014 12:38:05 CEST
#      REVISION:  ---
#===============================================================================

# set -o nounset                              # Treat unset variables as an error

rootDir="$HOME"
if [ "$1" != "" ]
then
  rootDir=$(realpath "$1")
fi

red='\e[0;31m'
green='\e[0;32m'
yellow='\e[0;33m'
NC='\e[0m' # No Color

#jq ".GIT" <<< "{\"GIT\":[[\"name\",\"Git\"],[\"command\",\"git\"],[\"configDir\",\".git\"],[\"updateCommand\",\"pull\"]]}"

if [ "$(command -v git)" == "" ]
then
  echo -e "${red}git not installed${NC}"
else
  # GIT source code management system
  echo -e "${green}***** Checking GIT repositories in ${yellow}$rootDir${NC}"
  echo
  find "$rootDir" -type d -name .git | sort | while read line; do
    workingDir=$(dirname "$line")
    echo -e "${green}GIT: ${NC}${yellow}$workingDir${NC}"
    cd "$workingDir"
    echo -e "${green}$(git pull)${NC}"
    echo
  done
fi


if [ "$(command -v svn)" == "" ]
then
  echo -e "${red}svn not installed${NC}"
else
  # Subversion source code management system
  echo -e "${green}***** Checking SVN repositories in ${yellow}$rootDir${NC}"
  echo
  find "$rootDir" -type d -name .svn | sort | while read line; do
    workingDir=$(dirname "$line")
    echo -e "${green}SVN: ${NC}${yellow}$workingDir${NC}"
    cd "$workingDir"
    echo -e "${green}$(svn update)${NC}"
    echo
  done
fi

if [ "$(command -v hg)" == "" ]
then
  echo -e "${red}hg not installed${NC}"
else
  # Mercurial source code management system
  echo -e "${green}***** Checking HG repositories in ${yellow}$rootDir${NC}"
  echo
  find "$rootDir" -type d -name .svn | sort | while read line; do
    workingDir=$(dirname "$line")
    echo -e "${green}HG: ${NC}${yellow}$workingDir${NC}"
    cd "$workingDir"
    echo -e "${green}$(hg pull)${NC}"
    echo
  done
fi

if [ "$(command -v bzr)" == "" ]
then
  echo -e "${red}bzr not installed${NC}"
else
  # BZR source code management system
  echo -e "${green}***** Checking BZR repositories in ${yellow}$rootDir${NC}"
  echo
  find "$rootDir" -type d -name .bzr | sort | while read line; do
    workingDir=$(dirname "$line")
    echo -e "${green}BZR: ${NC}${yellow}$workingDir${NC}"
    cd "$workingDir"
    echo -e "${green}$(bzr pull)${NC}"
    echo
  done
fi
