#!/bin/bash -
#===============================================================================
#
#          FILE: savepoweroff
#
#         USAGE: ./savepoweroff
#
#   DESCRIPTION:
#
#       OPTIONS: ---
#  REQUIREMENTS: ---
#          BUGS: ---
#         NOTES: ---
#        AUTHOR: Andreas Böttger (aboettger), andreas.boettger@gmx.de
#  ORGANIZATION:
#       CREATED: 12.04.2014 23:53
#      REVISION:  ---
#===============================================================================

#set -o nounset                              # Treat unset variables as an error
#set -o errexit

#red="\e[0;31m"
green="\e[0;32m"
yellow="\e[0;33m"
TOA="\e[0m" # No Color

minUptime=3600000
uptime=$(awk '{print $1*1000}' /proc/uptime)
uptimeHuman=$(uptime -p)

pidwget=$(ps -C wget -o pid=)
pidrsync=$(ps -C rsync -o pid=)
pidaria2c=$(ps -C aria2c -o pid=)

secUp=$(awk '{print $1 * 1000}' /proc/uptime)
userLen=$(last | grep -c "still logged in")

echo
echo -e "PID [${green}wget${TOA}]: ${yellow}$pidwget${TOA}"
echo -e "PID [${green}rsync${TOA}]: ${yellow}$pidrsync${TOA}"
echo -e "PID [${green}aria2c${TOA}]: ${yellow}$pidaria2c${TOA}"
echo
echo -e "Users: \c"; if [ "$userLen" -eq 0 ]; then echo -e "${green}$userLen${TOA}"; else echo -e "${yellow}$userLen${TOA}"; fi
echo -e "${yellow}$(last -w | grep "still logged in")${TOA}"
echo
echo -e "Uptime (ms) [${green}$minUptime${TOA}]: \c"; if [ "$secUp" -gt $minUptime ]; then echo -e "${green}$uptime ($uptimeHuman)${TOA}"; else echo -e "${yellow}$uptime ($uptimeHuman)${TOA}"; fi
echo

# mehr als eine Stunde uptime
if [ "$secUp" -gt $minUptime ] && [ "$pidrsync" == "" ] && [ "$pidaria2c" == "" ] && [ "$pidwget" == "" ]
then
  if [ "$userLen" -eq 0 ]
  then
    /sbin/shutdown -P now
    echo -e "${green}shutdown${TOA}"
  else
    echo -e "${yellow}no shutdown (users > 0)${TOA}"
  fi
else
  echo -e "${yellow}no shutdown (users > 0 | uptime < $minUptime | PID [rsync] > 0 | PID [aria2c] > 0 | PID [wget] > 0)${TOA}"
fi
echo
exit 0
