#!/bin/bash

command -v rtcwake >/dev/null 2>&1 || { echo "\"rtcwake\" required, but not installed."; exit 1; }

a=$(($(date -d "5" "+%s") - $(date -d "0" "+%s")))
b=$(($(date "+%s") - $(date -d "0" "+%s")))

if [ $((b - a)) -lt 0 ]; then
  echo "Start on the same day"
  $(which rtcwake) -m no --time "$(date -d "5" +%s)"
else
  echo "Start on the next day"
  $(which rtcwake) -m no --time "$(date -d "5 +24 hours" +%s)"
fi

cat /proc/driver/rtc

exit 0
