#!/bin/bash
#
# Scans the given directory and all subdirectories for the file
# "metadata.opf". This file is created by Calibre. From this file data will be
# extracted (title, author, series, keywords) and inserted into the PDFs, which are
# exactly in the same directory.


shopt -s nullglob
shopt -s nocaseglob

write_title() {
  red="\e[0;31m"
  green="\e[0;32m"
  NC="\e[0m" # No Color
  
  find "$1" -depth -type f -name "metadata.opf" | { while read -r metadata_path;
    do
      echo -e "${green}metadata found:${NC} $metadata_path"
      dir_name=$(dirname "$metadata_path")
      
      series=$(xpath -q -e "//package/metadata/meta[@name='calibre:series']/@content" "$metadata_path" | awk -F "content=" '{print $2}' | sed 's/^\"*//;s/\"*$//')
      series_index=$(xpath -q -e "//package/metadata/meta[@name='calibre:series_index']/@content" "$metadata_path" | awk -F "content=" '{print $2}' | sed 's/^\"*//;s/\"*$//')
      
      title=$(xpath -q -e "//package/metadata/dc:title/text()" "$metadata_path")
      author=$(xpath -q -e "//package/metadata/dc:creator/text()" "$metadata_path")
      keywords=$(xpath -q -e "//package/metadata/dc:subject/text()" "$metadata_path")
      
      pdfs=$(find "$dir_name" -maxdepth 1 -type f -name '*.pdf' | wc -l)
      
      echo -e "${green}pdfs found:${NC} $pdfs"
      
      find "$dir_name" -maxdepth 1 -type f -name "*.pdf" | { while read -r pdf_path;
        do
          titlePDF=$(pdfinfo "$pdf_path" | grep "Title" | awk '{sub(/[^ ]+ /, ""); print $0}' | sed 's/^[ \t]*//;s/[ \t]*$//')
          authorPDF=$(pdfinfo "$pdf_path" | grep "Author" | awk '{sub(/[^ ]+ /, ""); print $0}' | sed 's/^[ \t]*//;s/[ \t]*$//')
          keywordsPDF=$(exiftool -S -Keywords "$pdf_path" | grep "Keywords" | awk '{sub(/[^ ]+ /, ""); print $0}' | sed 's/\./\n/g' | sed 's/^[ \t]*//;s/[ \t]*$//')

          newTitle="$title $series_index"
          newAuthor="$author"
          newKeywords="$keywords"
          
          if [ "$titlePDF" == "$newTitle" ] && [ "$authorPDF" == "$newAuthor" ] && [ "$keywordsPDF" == "$newKeywords" ]
          then
            echo -e "\t${green}no update required.${NC}"
          else
            if [ "$titlePDF" != "$newTitle" ]
            then
              exiftool -overwrite_original -Title="$newTitle" "$pdf_path"
              echo -e "\t${green}updating title with:${NC} $newTitle"
            fi
            if [ "$authorPDF" != "$newAuthor" ]
            then
              exiftool -overwrite_original -Author="$newAuthor" "$pdf_path"
              echo -e "\t${green}updating author with:${NC} $newAuthor"
            fi
            if [ "$keywordsPDF" != "$newKeywords" ]
            then
              exiftool -overwrite_original -Keywords="$newKeywords" "$pdf_path"
              echo -e "\t${green}updating keywords with:${NC} $newKeywords"
            fi
          fi
        done
        echo
      }
    done
  }
}

[[ -z "$1" ]] && echo "Please specify a start directory." && exit 1

write_title "$1"
notify-send "$(basename $0)" 'done'

exit 0





